### PR TITLE
Use process.resourcesPath instead of process.cwd

### PR DESCRIPTION
**Pull request by bcomnes**

### CODE REVIEW

**Comment by maxogden** [comment]
published as 2.0.9

**Comment by matthewmueller** [comment]
Hm, this seems to break the example. `index.html` is no longer being served for some reason and it just shows up as blank.

**Comment by bcomnes** [comment]
Uh oh.  I'll retest it.

**Comment by bcomnes** [comment]
Still works when you npm run, but building an app results in the same thing we were seeing before the patch.  I'll fiddle around with it.

**Comment by bcomnes** [comment]
@matthewmueller for now just use the workaround in https://github.com/maxogden/monu/blob/master/index.js#L17

I need a way to get the devtools open again.

**Pull request merged**
