### PR TITLE
fix: Correct position on Windows & multi-taskbar

### LINKED ISSUE #67: Menu doesn't show on Windows 10
The menu doesn't show up on Windows 10: https://github.com/jingweno/hacker-menu/issues/18#issuecomment-141335512

### LINKED ISSUE #80: Windows (10). Doesn't show up properly with taskbar placements
When the taskbar is not positioned to the bottom or the right, the popup show up in the opposite corner (as if the taskbar was in those positions). 

Screenshot #1
Screenshot #2

I don't have enough experience with JavaScript and Node.js, so I can't offer a pull request to fix it.

### LINKED ISSUE #184: Incorrect position when tray is on the left on Windows
default

- Windows 10
- menubar 5.2.3

### LINKED ISSUE #196: How to detect if tray bar is on top|left|bottom|right
I am showing an arrow, like in #78. However, in the renderer webpage, I need to detect the position of the tray bar, to render the correct arrow.

In the main process, how can I detect the position of the tray bar?

### LINKED ISSUE #206: Menubar not reliably positioned next to the tray area on Windows and on multi-monitor setup
Hey @amaurymartiny,
Great to see someone taking care of this repo :)

I've had issues with current master branch. Specifically, 1) the menubar is not reliably positioned next to the tray area on Windows (when start menu is moved all around the screen), and 2) menubar is not correctly positioned when using a multi-monitor setup, depending on where the 2nd monitor is (at least on Mac, maybe on Windows as well).

Luckily, both these issues are resolved with this branch: [`sidneys/menubar/add-taskbar-support`](https://github.com/sidneys/menubar/tree/add-taskbar-support).

I tried to compare your PR with this branch, but because it's been rewritten extensively, I'm not sure it's included. Here's the [comparison with current master](https://github.com/maxogden/menubar/compare/master...sidneys:add-taskbar-support).

Do you know if at least the traybar positioning issue on Windows is fixed with your fork?

_Originally posted by @julienma in https://github.com/maxogden/menubar/pull/203#issuecomment-497629242_

### PR DESCRIPTION
**Pull request by amaurymartiny**
This is a port of https://github.com/maxogden/menubar/compare/master...sidneys:add-taskbar-support to the new TS refactoring. All credits go to @sidneys.

fixes #206 
fixes #196 
fixes #184
fixes #67 
fixes #80

cc @julienma.

I believe some stuff could go into `electron-positioner`, but as I don't see any activity there, I'll just put it here. cc @jenslind.

I'll just find a Windows to test this before merging it (if anyone else wants to test, it'd be even better!)

### CODE REVIEW

**Comment by julienma** [comment]
Oooh, exciting! I'll have a look next week.
Won't be able to test on Windows in a timely fashion though.

Thanks Amaury.

**Comment by jenslind** [comment]
Hey! Nice to see someone working on this! 😃 

I believe the taskbar location detection should be in here and not in `electron-positioner`.
But we might want the "Multi-Taskbar: optimize vertical position" fix in `electron-positioner` instead.
I'm not 100% sure what issue it fixes though :)

**Comment by amaurymartiny** [comment]
Works well on macOS and windows! Didn't test on multi-monitor though.

**Comment by julienma** [comment]
\o/
Thanks Amaury, will try in our app.

**Comment by tboulis** [comment]
@amaurymartiny I have an issue with multi monitor setup.
### Setup
- Windows 10 Pro, 3 monitors (1 laptop, 2 standalone)
- Windows task bar is on the right side of the screen (vertical)

### What happens:
The menubar window is not full visible (bottom is getting cut off)

image

**Comment by amaurymartiny** [comment]
thanks @tboulis! could you create a separate issue to track this?

Also, do you have a fix in mind?

**Comment by tboulis** [comment]
I'll create a new issue @amaurymartiny no worries!
I just bumped into it, and found this PR! 

I don't have a fix in mind, but I'll try to figure something out

**Pull request merged**
