### PR TITLE
Update peerDeps for Electron 22

### PR DESCRIPTION
**Pull request by wesbos**
Tested with 22 and it works great

### CODE REVIEW

**Comment by danielzev** [comment]
any update on merging this?

**Comment by amaurym** [comment]
@wesbos Can you update the devDependencies, yarn.lock, `examples/` folder and README too? Thanks!

**Comment by danielzev** [comment]
@wesbos I see this was created yesterday https://github.com/maxogden/menubar/pull/412

@amaurym is there a rough timeline for this to merge in?

**Comment by amaurym** [comment]
I'm fine to merge this as soon as https://github.com/maxogden/menubar/pull/404#issuecomment-1368998928 is addressed!

@wesbos seems like he's not replying, @danielzev would you like to create a new PR?

**Comment by mnrdrata** [comment]
@amaurym @danielzev Will this work https://github.com/maxogden/menubar/pull/414?

**Comment by amaurym** [comment]
Superesed by #414

**Pull request closed without merging**
