### PR TITLE
Show window on dock icon click

### LINKED ISSUE #278: Should the dock icon open the app?
We have the `showDockIcon` option, but it seems clicking the dock icon does not show the app. Should it should the app or is the icon solely to show it is running? I would love to be able to open the app from the dock icon and have the window show.

### PR DESCRIPTION
**Pull request by rwwagner90**
Closes #278

### CODE REVIEW

**Comment by rwwagner90** [comment]
@amaurymartiny it keeps telling me `this.app.on` is not a function. Any ideas?

**Comment by amaurymartiny** [comment]
Ah yeah, for tests, we mock the Electron app object. In `src/mocks/electron.ts`, could you please add:
```diff
export const app = {
  getAppPath: jest.fn(() => MOCK_APP_GETAPPPATH),
  isReady: (): Promise<void> => Promise.resolve(),
+  on: (): void => {
+   /* Do nothing */
+  }
};
```

**Comment by rwwagner90** [comment]
@amaurymartiny updated, thanks!

**Comment by rwwagner90** [comment]
@amaurymartiny thanks for merging! When do you think a new release will be out with these changes?

**Comment by amaurymartiny** [comment]
8.0.2 is out!

**Pull request merged**
