### PR TITLE
Work around Electron display focus issues

### PR DESCRIPTION
**Pull request by russellhaering**
Fixes issue #19 

Works around this bug in Electron: https://github.com/atom/electron/issues/1847

This should keep working once that issue is resolved.

### CODE REVIEW

**Comment by maxogden** [comment]
nice. though im kind of hesitant to merge a hack that might be fixed in a relatively short amount of time. if it turns out https://github.com/atom/electron/issues/1847 is a wontfix then this can go in, but for now if someone has this issue they should just use your fork, i'll leave this PR open for visibility

**Comment by fabien-d** [comment]
We're running into the same issue. This PR is out of date so we can't use it since we need things that have been merged since. The current `clicked` method we're using [pretty much the same as this PR]

```js
function clicked (e, bounds) {
  if (menubar.window && menubar.window.isVisible()) return hideWindow()

  // workarea takes the taskbar/menubar height in consideration
  var activeWorkArea = electronScreen.getDisplayNearestPoint(electronScreen.getCursorScreenPoint()).workArea

  if (bounds) cachedBounds = bounds

  // ensure bounds is an object
  bounds = bounds || {}

  // default to bottom on windows if `bounds.y` is not set
  // leave it open to use prepopulated `bounds` if/when windows sets it
  if (process.platform === 'win32' && bounds.y === 0) bounds.y = activeWorkArea.height - opts.height

  if (bounds.x === 0) {
    // default to right
    bounds.x = activeWorkArea.width + activeWorkArea.x - (opts.width / 2)
  } else {
    var boundsWorkArea = electronScreen.getDisplayNearestPoint(bounds).workArea
    // make sure it's a different screen before modifying the bounds object
    if ( boundsWorkArea.x !== activeWorkArea.x ) {
      var offsetX = boundsWorkArea.x + boundsWorkArea.width - bounds.x
      bounds.x = activeWorkArea.width + activeWorkArea.x - offsetX
    }
  }

  cachedBounds = bounds
  showWindow(cachedBounds)
}
```

**Comment by fabien-d** [comment]
A small note on the above, it takes the `y` position into consideration as well. My home setup has my external display above my laptop [vertical stack] and adjusting only the `x` value aligned it properly horizontally but would remain on the "focused" display not [necessarily] the "active" vertically.

This has not [yet] been tested on Windows 8+, which allow the taskbar on external display.

Are you still hesitant to get this into core? + @maxogden. There doesn't appear to be much friction on the opened electron issue.

**Comment by maxogden** [comment]
Yea since that Electron issue has no activity lately I'd be okay with you putting in a temporary fix. Just make the temporary part easy to remove later (e.g. in it's own function w/ a comment)

**Pull request closed without merging**
