### PR TITLE
fix: Get taskbar location on linux

### LINKED ISSUE #123: Window position completely incorrect on Linux
Tested using the example app in this repository, on openSUSE 13.1 (64-bits), using XFCE4 (xfce4-panel 4.10.1), and the Electron version as it is installed from the example's package.json.

When clicking the tray icon, the window opens in the top right corner, rather than anywhere near the tray icon:

selection_622

It does however open on the correct monitor (specifically, the left monitor, which my panel is also displayed on).

### PR DESCRIPTION
**Pull request by amaurymartiny**
fixes #123

### CODE REVIEW

**Comment by evertonfraga** [comment]
Hey :)

how can we unfreeze this PR? We can test it on ubuntu, if that helps.

**Comment by amaurymartiny** [comment]
@evertonfraga Unfrozen. I'll spin up some linux VM this weekend to test thoroughly (the current changes are 100% untested).

If you test and want to create a fork before that, please do, and I'll close mine. It's really just empirically testing menubar location with [one of these values](https://github.com/jenslind/electron-positioner#position).

**Comment by amaurymartiny** [comment]
Unfortunately this won't work because of https://github.com/electron/electron/issues/15003. I'm closing this, we'll always show the window in the top right corner for now.

**Comment by vigneshwaran-chandrasekaran** [comment]
screen.getCursorScreenPoint() to get screen click cursor pointer and use it instead of tray icon bounds

**Pull request closed without merging**
