### PR TITLE
Add windows support

### PR DESCRIPTION
**Pull request by fabien-d**
#### What does this PR do?
* Add Windows support
* Position menubar window at the bottom right

#### How should this be manually tested?
1. Run the example application on Windows.
2. Replace `index.js` file in `example/node_modules/menubar` dependency

#### Any background context you want to provide?
I use `getDisplayNearestPoint` instead of `getPrimaryDisplay` to make the application open on the proper display (issue https://github.com/maxogden/menubar/issues/19). The code could be updated to use this regardless if `bounds` is set. Not ideal since there is a fix [potential] incoming in Electron core (https://github.com/atom/electron/issues/1847).

#### Related issue
- https://github.com/maxogden/menubar/issues/1

### CODE REVIEW

**Comment by maxogden** [comment]
@fabien-d nice, looks good. only issue is with code style, check out the travis output

**Comment by fabien-d** [comment]
Rebased with code style updates.

**Comment by maxogden** [comment]
thanks! released as 2.0.12

**Comment by fabien-d** [comment]
:+1:

**Pull request merged**
