### PR TITLE
Improve 'windows' OS detection of taskbar location

### PR DESCRIPTION
**Pull request by semenov-oleg**
Should be helpful for the following issues
https://github.com/maxogden/menubar/issues/264
https://github.com/maxogden/menubar/issues/232

### CODE REVIEW

**Review by amaurymartiny — COMMENTED** [review]
this looks sensible to me, though I'd like to test this before merging.

@adam-lynch  would you be able to give a test?

@semenov-oleg could you fix the linting errors? (Running `yarn lint --fix` from the root folder should do)

**Comment by semenov-oleg** [comment]
Sure, updated PR

**Comment by garbageoverflow** [comment]
fix ur program. https://github.com/maxogden/menubar/issues/309

**Comment by asparamancer** [comment]
Is this going to be merged into an official release?

**Comment by rwwagner90** [comment]
@amaurymartiny we have users reporting this bug when the taskbar is on the left as well. Any chance we could get this merged and released? I'm happy to help test as well if needed.

**Comment by amaurymartiny** [comment]
I unfortunately didn't get the chance to test on Windows. It seems that it's blocking a couple of users, so I am going to merge it. Thanks @semenov-oleg for the work!

**Review by amaurymartiny — APPROVED** [review]

**Comment by rwwagner90** [comment]
@amaurymartiny it seems that left sided taskbars are still broken with this PR, according to some users.

**Comment by vicke4** [comment]
#343 fixes the left-sided taskbar issue.

**Pull request merged**
