### PR TITLE
Center window under tray icon

### PR DESCRIPTION
**Pull request by jenslind**

### CODE REVIEW

**Comment by maxogden** [comment]
nice, looks like this was implemented 3 days ago https://github.com/atom/electron/pull/1568 but hasn't been released yet https://github.com/atom/electron/releases

**Comment by maxogden** [comment]
tests failed because `/home/travis/build/maxogden/menubar/index.js:27:8: atomScreen is defined but never used`, e.g. you just need to remove the `require('screen')` stuff now that it isnt used

**Comment by jenslind** [comment]
Yeah its not released yet. :)

Fixed the unused require..

**Comment by maxogden** [comment]
alright sweet, ill merge now but wont publish to npm until its released

**Comment by jenslind** [comment]
nice :+1:

**Comment by jenslind** [comment]
Looks like this has been released now.
https://github.com/atom/electron/releases/tag/v0.25.3

**Comment by jenslind** [comment]
@maxogden is there a reason this hasn't been released yet? :shipit: :cat:

**Comment by maxogden** [comment]
its out as 2.0.5

:D

**Comment by jenslind** [comment]
Nice! Aaand btw this closes https://github.com/maxogden/menubar/issues/8 ;)

**Pull request merged**
