### PR TITLE
add sketch icon template

### PR DESCRIPTION
**Pull request by zeke**
Platform specific, so maybe not ideal. But could be useful for some people. `¯\_(ツ)_/¯`

### CODE REVIEW

**Comment by amaurymartiny** [comment]
Hey @zeke, I think this can still be useful for some people. Could you rebase on master, and put the .sketch inside the assets/ folder?

**Comment by zeke** [comment]
Done!

**Comment by amaurymartiny** [comment]
Hey @zeke, thanks for the fast response, but I can't merge the PR as-is:
- The README seems to be completely deleted
- could you add the .sketch file into `assets/` instead of `examples/`?

Thanks!

**Comment by zeke** [comment]
Sorry something went haywire in the rebase. I'll take a look.

**Comment by evertonfraga** [comment]
I can be mistaken (old Sketch version and all), but it seems the file only contains this:

image

**Comment by amaurymartiny** [comment]
closing as stale

**Pull request closed without merging**
