### PR TITLE
Make `showWindow()` calculate bounds and positioning.

### PR DESCRIPTION
**Pull request by Tribex**
Calls to `showWindow()` now calculate the bounds and position of the window/tray icon in the same method as clicking on the tray icon (if no argument is specified).

Tray bounds default to:
```javascript
{
  x: 0,
  y: 0,
  width: 0,
  height: 0
}
```

The position of `menubar.window.show()` and `menubar.window.setPosition(x, y)` in `showWindow()` have been swapped as well, to eliminate flashing when the window changes position during runtime.

Works fine for me under Ubuntu 15.04, GNOME 3.16 (with TopIcons extension), and Electron v0.30.4. Might want to test on other platforms though.

The motivation behind this PR is simply to allow opening of the window by other methods (eg. keyboard shortcuts) in the same position as clicking on the tray icon.

Hope this is of use! Excellent module by the way.

### CODE REVIEW

**Comment by jenslind** [comment]
Thanks! However I think we should wait for https://github.com/maxogden/menubar/pull/54 and then if the tray bounds is empty, default the window to top right and bottom right on Windows.

**Comment by Tribex** [comment]
@jenslind Sure, I'm actually using electron-positioner in another part of the project. (You can use the two together at the moment.)

@maxogden Opinion?

**Comment by jenslind** [comment]
Closing this, as of `2.2.1` you can now use `mb.showWindow` without tray bounds being set (it defaults to the right).

**Comment by Tribex** [comment]
Alright. Thanks!

**Pull request closed without merging**
