### PR TITLE
add `before-load` event

### PR DESCRIPTION
**Pull request by Araxeus**
With [`@electron/remote`](https://www.npmjs.com/package/@electron/remote) and Electron >= 14
we  must use the new enable API to enable the remote module for each desired WebContents separately: `require("@electron/remote/main").enable(webContents)`

The problem is that this enable function needs to be executed 
* after the BrowserWindow is created - (after `emit('create-window')`) 
* before `browserWindow.loadURL()` is called - (before `emit('after-create-window')`)

This new `before-load` event is perfect for this  (Tested and it fixes the problem)

Notes:

* from what I know, `@electron/remote` can't work without this PR, so would be great if this could be merged and a new hotfix version released @maxogden
* #366 tries to do the same thing but this PR keeps backward compatibility by defining a new separate event
* Typescript was updated because I was getting compilation errors

### CODE REVIEW

**Comment by Araxeus** [comment]
@maxogden any thoughts? could this be merged?

**Comment by Araxeus** [comment]
@amaurym thoughts?

**Review by amaurym — APPROVED** [review]

**Comment by amaurym** [comment]
Thanks!

**Comment by amaurym** [comment]
Published in v9.2.0

**Pull request merged**
