### PR TITLE
Use app.getAppPath() as default path

### PR DESCRIPTION
**Pull request by jenslind**
Fixes https://github.com/maxogden/menubar/issues/30

### CODE REVIEW

**Comment by jenslind** [comment]
@maxogden could you review this please? :sunny:

**Comment by maxogden** [comment]
@jenslind cool, LGTM

**Comment by maxogden** [comment]
@jenslind I added you as an owner here + on github so feel free to merge and release this :)

**Comment by jenslind** [comment]
Cool, thanks!

**Comment by jenslind** [comment]
Released in `v2.0.17`

**Pull request merged**
